### ISSUE TITLE
CSV to Image processing weirdness - DeepSat Sat6

### ISSUE THREAD

**Issue by tolandwehr** [kkgadiraju/SAT-Classification-Using-CNN#1]
Hi there,

finally found something to read in the DeepSat Sat6 data set ( http://csc.lsu.edu/~saikat/deepsat/) provided by @kkgadiraju (SAT-Classification-Using-CNN/Preprocessing-SAT6.ipynb). However, I'm, not sure, whether the image output is correct.

Here is  @kkgadiraju  respective code:

```
data = sio.loadmat('/home/gadiraju/data/bl-slums/sat-6-full.mat')
train_X = data['train_x'].transpose()
train_Y = data['train_y'].transpose()
test_X = data['test_x'].transpose()
test_Y = data['test_y'].transpose()
annotations = data['annotations']

print train_X.shape, train_Y.shape, test_X.shape, test_Y.shape, annotations

train_X = train_X.reshape(train_X.shape[0], 28,28,4)
test_X = test_X.reshape(test_X.shape[0],28,28,4)full 

print train_X.shape, test_X.shape
```

When I try to visualize it with

```
ix =100001#Type a number between 0 and 323,999 inclusive
imshow(np.squeeze(train_X[ix,:,:,0:3]).astype(int)) #Only seeing the RGB channels
plt.show()
#Tells what the image is
if train_Y[ix,0] == 1:
    print ('Barren Land')
elif train_Y[ix,1] == 1:
    print ('Trees')
elif train_Y[ix,2] == 1:
    print ('Grassland')
elif train_Y[ix,3] == 1:
    print ('Roads')
elif train_Y[ix,4] == 1:
    print ('Buildings')
elif train_Y[ix,5] == 1:
    print ('Water Body')
else:
    print ('Other')
```

the resulting image is somewhat odd and patterned estranged, not showing actually what is labelled (in my opinion). Anybody there who knows the issue? Guess its just a minor one, but I somewhat do not notice, what it is.

**Comment by tolandwehr** [comment]
I just skippted the whole transposing and reshaping, resulting in what a nice images. Case closed.

**Comment by kkgadiraju** [comment]
Yo're right. if you're just looking for visualization, you don't transpose the data (transpose converts it to n_images x 4 x 28 x 28.) Transpose is being done to set it up for the NN later.

**Comment by tolandwehr** [comment]
The reason for preprocessong lies in the cnn structure of keras, am I right? Or is there more to it?Greets,TobiasAm 19.07.2018 02:31 schrieb Krishna Karthik Gadiraju <notifications@github.com>:Yo're right. if you're just looking for visualization, you don't transpose the data (transpose converts it to n_images x 4 x 28 x 28.

**Comment by kkgadiraju** [comment]
We're using TFLearn, not keras in this repo. And yes, because you want to send the input to your cnn as number of channels x image width x image height. There are other ways to do it as well.
